### PR TITLE
Add 'Have Faith In Dutch', 'Wabbit Season' and 'You sir, are a fish' effects

### PR DESCRIPTION
**Pull request by chrisschwartzdev**
Have Faith In Dutch:
* Simply spawns Dutch as a companion with his revolver.

Wabbit Season:
* Spawns a max of 10 rabbits that chase the player and "attack" if they're close enough.
* More rabbits will spawn if any die or move out of distance to maintain a count of 10.
* Since rabbits do not have attacking ability, the players health is subtracted from if they are close enough with an audio cue.
* Only one rabbit is allowed to damage the player every 2 seconds, to keep it somewhat fair.
* All rabbits are despawned when the timer is up.
* I tried to prevent the rabbits from fleeing ever, but they still sometimes do if a rabbit is killed (any ideas on how to handle that better, let me know!)

You sir, are a fish:
* Replaces all nearby enemies with fish.

### CODE REVIEW

**Comment by Jaydawg8888** [comment]
> I tried to prevent the rabbits from fleeing ever, but they still sometimes do if a rabbit is killed (any ideas on how to handle that better, let me know!)

For the rabbits you could try setting  `SET_BLOCKING_OF_NON_TEMPORARY_EVENTS ` to **true** after spawning the rabbit - This might make them stick to their current TASK_COMBAT_PED, as they should ignore all other events around them?

**Comment by chrisschwartzdev** [comment]
@Jaydawg8888 Thanks, that worked perfectly! That effect is so much better when the rabbits don't flee, haha.

**Comment by Jaydawg8888** [comment]
@chrisschwartzdev Awesome, glad that helped fix your issue (:

Testing out your additions, I noticed for 'Wabbit Season' that there didn't appear to be any rabbits spawning at all for me.

From further testing it seems that if you're in an area that doesn't have any rabbits spawned then it doesn't work as the model hasn't been loaded.

I'd suggest probably doing:
`LoadModel(rabbitSkinModel);`

In your `EffectSpawnKillerBunnyHorde::OnActivate`

Then in `EffectSpawnKillerBunnyHorde::OnDeactivate` using to unload the model `STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED`

Other than that I love the effect and everything else seems good!

**Comment by chrisschwartzdev** [comment]
Closed this PR as I'll be pushing all of my effects in a new PR.

**Pull request closed without merging**
